# Generated by Django 3.2.3 on 2021-05-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing2',
            name='file',
            field=models.FileField(default=None, max_length=30, upload_to=''),
            preserve_default=False,
        ),
    ]
